---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - lab.security.lab
  resources:
  - vulnerablelabs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - lab.security.lab
  resources:
  - vulnerablelabs/finalizers
  verbs:
  - update
- apiGroups:
  - lab.security.lab
  resources:
  - vulnerablelabs/status
  verbs:
  - get
  - patch
  - update
