apiVersion: lab.security.lab/v1alpha1
kind: VulnerableLab
metadata:
  namespace: test-lab
  name: vulnerablelab
spec:
  vulnerability: K02
  subIssue: 3  # Payment-service vulnerable image (ruby:3.0-alpine)